import { Scenario } from '../types/index.js';

export const stadiumScenario: Scenario = {
  id: 'stadium',
  name: 'Stadium Match Day',
  description: 'A 40,000-seat stadium with main gates, concourses, and exits. Simulates crowd flow during match entry with a natural bottleneck at the north corridor.',
  seed: 42,
  stepDuration: 10,
  totalSteps: 120,
  venue: {
    nodes: [
      { id: 'north_gate', label: 'North Gate', type: 'gate', position: { x: 300, y: 50 }, capacity: 800, throughput: 50 },
      { id: 'south_gate', label: 'South Gate', type: 'gate', position: { x: 300, y: 550 }, capacity: 800, throughput: 50 },
      { id: 'east_gate', label: 'East Gate', type: 'gate', position: { x: 550, y: 300 }, capacity: 600, throughput: 40 },
      { id: 'west_gate', label: 'West Gate', type: 'gate', position: { x: 50, y: 300 }, capacity: 600, throughput: 40 },
      { id: 'junction_n', label: 'Junction N', type: 'junction', position: { x: 300, y: 150 } },
      { id: 'junction_s', label: 'Junction S', type: 'junction', position: { x: 300, y: 450 } },
      { id: 'junction_e', label: 'Junction E', type: 'junction', position: { x: 450, y: 300 } },
      { id: 'junction_w', label: 'Junction W', type: 'junction', position: { x: 150, y: 300 } },
      { id: 'corridor_n', label: 'Corridor N', type: 'corridor', position: { x: 300, y: 200 } },
      { id: 'corridor_s', label: 'Corridor S', type: 'corridor', position: { x: 300, y: 400 } },
      { id: 'corridor_e', label: 'Corridor E', type: 'corridor', position: { x: 400, y: 300 } },
      { id: 'corridor_w', label: 'Corridor W', type: 'corridor', position: { x: 200, y: 300 } },
      { id: 'food_n', label: 'Food Court N', type: 'food', position: { x: 250, y: 250 } },
      { id: 'food_s', label: 'Food Court S', type: 'food', position: { x: 350, y: 350 } },
      { id: 'toilet_e', label: 'Toilets E', type: 'toilet', position: { x: 480, y: 250 } },
      { id: 'toilet_w', label: 'Toilets W', type: 'toilet', position: { x: 120, y: 350 } },
      { id: 'stage', label: 'Main Stage', type: 'stage', position: { x: 300, y: 300 } },
      { id: 'exit_n', label: 'Exit N', type: 'exit', position: { x: 300, y: 20 } },
      { id: 'exit_s', label: 'Exit S', type: 'exit', position: { x: 300, y: 580 } },
      { id: 'exit_e', label: 'Exit E', type: 'exit', position: { x: 580, y: 300 } },
      { id: 'exit_w', label: 'Exit W', type: 'exit', position: { x: 20, y: 300 } },
      { id: 'emergency_ne', label: 'Emergency NE', type: 'emergency', position: { x: 500, y: 100 } },
      { id: 'emergency_sw', label: 'Emergency SW', type: 'emergency', position: { x: 100, y: 500 } },
    ],
    edges: [
      { id: 'e_north_jn', from: 'north_gate', to: 'junction_n', length: 50, width: 8, capacity: 60, baseTravelTime: 30, bidirectional: true },
      { id: 'e_south_js', from: 'south_gate', to: 'junction_s', length: 50, width: 8, capacity: 60, baseTravelTime: 30, bidirectional: true },
      { id: 'e_east_je', from: 'east_gate', to: 'junction_e', length: 40, width: 6, capacity: 40, baseTravelTime: 25, bidirectional: true },
      { id: 'e_west_jw', from: 'west_gate', to: 'junction_w', length: 40, width: 6, capacity: 40, baseTravelTime: 25, bidirectional: true },
      { id: 'e_jn_corridor_n', from: 'junction_n', to: 'corridor_n', length: 30, width: 4, capacity: 18, baseTravelTime: 20, bidirectional: true },
      { id: 'e_js_corridor_s', from: 'junction_s', to: 'corridor_s', length: 30, width: 4, capacity: 18, baseTravelTime: 20, bidirectional: true },
      { id: 'e_je_corridor_e', from: 'junction_e', to: 'corridor_e', length: 30, width: 4, capacity: 15, baseTravelTime: 18, bidirectional: true },
      { id: 'e_jw_corridor_w', from: 'junction_w', to: 'corridor_w', length: 30, width: 4, capacity: 15, baseTravelTime: 18, bidirectional: true },
      { id: 'e_corridor_n_stage', from: 'corridor_n', to: 'stage', length: 60, width: 10, capacity: 80, baseTravelTime: 40, bidirectional: true },
      { id: 'e_corridor_s_stage', from: 'corridor_s', to: 'stage', length: 60, width: 10, capacity: 80, baseTravelTime: 40, bidirectional: true },
      { id: 'e_corridor_e_stage', from: 'corridor_e', to: 'stage', length: 60, width: 8, capacity: 60, baseTravelTime: 35, bidirectional: true },
      { id: 'e_corridor_w_stage', from: 'corridor_w', to: 'stage', length: 60, width: 8, capacity: 60, baseTravelTime: 35, bidirectional: true },
      { id: 'e_corridor_n_food_n', from: 'corridor_n', to: 'food_n', length: 20, width: 4, capacity: 25, baseTravelTime: 12, bidirectional: true },
      { id: 'e_corridor_s_food_s', from: 'corridor_s', to: 'food_s', length: 20, width: 4, capacity: 25, baseTravelTime: 12, bidirectional: true },
      { id: 'e_corridor_e_toilet_e', from: 'corridor_e', to: 'toilet_e', length: 15, width: 3, capacity: 15, baseTravelTime: 10, bidirectional: true },
      { id: 'e_corridor_w_toilet_w', from: 'corridor_w', to: 'toilet_w', length: 15, width: 3, capacity: 15, baseTravelTime: 10, bidirectional: true },
      { id: 'e_stage_exit_n', from: 'stage', to: 'exit_n', length: 80, width: 12, capacity: 100, baseTravelTime: 50, bidirectional: true },
      { id: 'e_stage_exit_s', from: 'stage', to: 'exit_s', length: 80, width: 12, capacity: 100, baseTravelTime: 50, bidirectional: true },
      { id: 'e_stage_exit_e', from: 'stage', to: 'exit_e', length: 80, width: 10, capacity: 80, baseTravelTime: 45, bidirectional: true },
      { id: 'e_stage_exit_w', from: 'stage', to: 'exit_w', length: 80, width: 10, capacity: 80, baseTravelTime: 45, bidirectional: true },
      { id: 'e_jn_emergency_ne', from: 'junction_n', to: 'emergency_ne', length: 70, width: 4, capacity: 30, baseTravelTime: 35, bidirectional: true },
      { id: 'e_js_emergency_sw', from: 'junction_s', to: 'emergency_sw', length: 70, width: 4, capacity: 30, baseTravelTime: 35, bidirectional: true },
    ],
  },
  agents: [
    { id: 'wave_north', originId: 'north_gate', destinationId: 'stage', count: 350, walkingSpeed: 1.2, arrivalTime: 0, route: ['north_gate', 'junction_n', 'corridor_n', 'stage'] },
    { id: 'wave_south', originId: 'south_gate', destinationId: 'stage', count: 280, walkingSpeed: 1.2, arrivalTime: 3, route: ['south_gate', 'junction_s', 'corridor_s', 'stage'] },
    { id: 'wave_east', originId: 'east_gate', destinationId: 'stage', count: 220, walkingSpeed: 1.1, arrivalTime: 8, route: ['east_gate', 'junction_e', 'corridor_e', 'stage'] },
    { id: 'wave_west', originId: 'west_gate', destinationId: 'stage', count: 220, walkingSpeed: 1.1, arrivalTime: 12, route: ['west_gate', 'junction_w', 'corridor_w', 'stage'] },
    { id: 'exit_north', originId: 'stage', destinationId: 'exit_n', count: 180, walkingSpeed: 1.3, arrivalTime: 55, route: ['stage', 'exit_n'] },
    { id: 'exit_south', originId: 'stage', destinationId: 'exit_s', count: 180, walkingSpeed: 1.3, arrivalTime: 58, route: ['stage', 'exit_s'] },
    { id: 'food_run', originId: 'stage', destinationId: 'food_n', count: 100, walkingSpeed: 1.0, arrivalTime: 35, route: ['stage', 'corridor_n', 'food_n'] },
  ],
};

export const festivalScenario: Scenario = {
  id: 'festival',
  name: 'Music Festival',
  description: 'An open-air festival with multiple stages, food trucks, and camping gates.',
  seed: 99,
  stepDuration: 15,
  totalSteps: 100,
  venue: {
    nodes: [
      { id: 'main_gate', label: 'Main Gate', type: 'gate', position: { x: 300, y: 50 } },
      { id: 'camp_gate', label: 'Camping Gate', type: 'gate', position: { x: 100, y: 50 } },
      { id: 'stage_a', label: 'Main Stage', type: 'stage', position: { x: 300, y: 200 } },
      { id: 'stage_b', label: 'Second Stage', type: 'stage', position: { x: 500, y: 200 } },
      { id: 'food_1', label: 'Food Truck 1', type: 'food', position: { x: 200, y: 350 } },
      { id: 'food_2', label: 'Food Truck 2', type: 'food', position: { x: 400, y: 350 } },
      { id: 'toilet_1', label: 'Toilet Block 1', type: 'toilet', position: { x: 150, y: 250 } },
      { id: 'toilet_2', label: 'Toilet Block 2', type: 'toilet', position: { x: 450, y: 250 } },
      { id: 'exit_main', label: 'Main Exit', type: 'exit', position: { x: 300, y: 500 } },
      { id: 'exit_camp', label: 'Camp Exit', type: 'exit', position: { x: 50, y: 500 } },
    ],
    edges: [
      { id: 'e_main_stage_a', from: 'main_gate', to: 'stage_a', length: 80, width: 10, capacity: 100, baseTravelTime: 60, bidirectional: true },
      { id: 'e_main_stage_b', from: 'main_gate', to: 'stage_b', length: 100, width: 8, capacity: 80, baseTravelTime: 75, bidirectional: true },
      { id: 'e_camp_stage_a', from: 'camp_gate', to: 'stage_a', length: 120, width: 6, capacity: 50, baseTravelTime: 90, bidirectional: true },
      { id: 'e_stage_a_food_1', from: 'stage_a', to: 'food_1', length: 60, width: 6, capacity: 40, baseTravelTime: 45, bidirectional: true },
      { id: 'e_stage_a_food_2', from: 'stage_a', to: 'food_2', length: 60, width: 6, capacity: 40, baseTravelTime: 45, bidirectional: true },
      { id: 'e_stage_b_food_2', from: 'stage_b', to: 'food_2', length: 50, width: 5, capacity: 35, baseTravelTime: 40, bidirectional: true },
      { id: 'e_stage_a_toilet_1', from: 'stage_a', to: 'toilet_1', length: 40, width: 4, capacity: 25, baseTravelTime: 30, bidirectional: true },
      { id: 'e_stage_b_toilet_2', from: 'stage_b', to: 'toilet_2', length: 40, width: 4, capacity: 25, baseTravelTime: 30, bidirectional: true },
      { id: 'e_food_1_exit', from: 'food_1', to: 'exit_main', length: 70, width: 8, capacity: 60, baseTravelTime: 50, bidirectional: true },
      { id: 'e_food_2_exit', from: 'food_2', to: 'exit_main', length: 70, width: 8, capacity: 60, baseTravelTime: 50, bidirectional: true },
      { id: 'e_food_1_exit_camp', from: 'food_1', to: 'exit_camp', length: 100, width: 5, capacity: 40, baseTravelTime: 70, bidirectional: true },
    ],
  },
  agents: [
    { id: 'main_rush', originId: 'main_gate', destinationId: 'stage_a', count: 400, walkingSpeed: 1.2, arrivalTime: 0, route: ['main_gate', 'stage_a'] },
    { id: 'camp_inflow', originId: 'camp_gate', destinationId: 'stage_a', count: 150, walkingSpeed: 1.0, arrivalTime: 10, route: ['camp_gate', 'stage_a'] },
    { id: 'stage_hop', originId: 'stage_a', destinationId: 'stage_b', count: 200, walkingSpeed: 1.1, arrivalTime: 30, route: ['stage_a', 'stage_b'] },
    { id: 'food_rush', originId: 'stage_a', destinationId: 'food_1', count: 120, walkingSpeed: 1.0, arrivalTime: 45, route: ['stage_a', 'food_1'] },
    { id: 'exit_wave', originId: 'stage_a', destinationId: 'exit_main', count: 300, walkingSpeed: 1.3, arrivalTime: 70, route: ['stage_a', 'food_1', 'exit_main'] },
  ],
};

export const railwayScenario: Scenario = {
  id: 'railway',
  name: 'Railway Station',
  description: 'A busy railway station with platforms, ticket gates, and concourses.',
  seed: 77,
  stepDuration: 10,
  totalSteps: 90,
  venue: {
    nodes: [
      { id: 'entry_1', label: 'Entry Gate 1', type: 'gate', position: { x: 150, y: 50 } },
      { id: 'entry_2', label: 'Entry Gate 2', type: 'gate', position: { x: 350, y: 50 } },
      { id: 'ticket_1', label: 'Ticket Counter 1', type: 'gate', position: { x: 150, y: 150 } },
      { id: 'ticket_2', label: 'Ticket Counter 2', type: 'gate', position: { x: 350, y: 150 } },
      { id: 'concourse', label: 'Main Concourse', type: 'junction', position: { x: 250, y: 250 } },
      { id: 'platform_1', label: 'Platform 1', type: 'stage', position: { x: 100, y: 400 } },
      { id: 'platform_2', label: 'Platform 2', type: 'stage', position: { x: 250, y: 400 } },
      { id: 'platform_3', label: 'Platform 3', type: 'stage', position: { x: 400, y: 400 } },
      { id: 'food_court', label: 'Food Court', type: 'food', position: { x: 500, y: 250 } },
      { id: 'exit_1', label: 'Exit 1', type: 'exit', position: { x: 50, y: 500 } },
      { id: 'exit_2', label: 'Exit 2', type: 'exit', position: { x: 450, y: 500 } },
    ],
    edges: [
      { id: 'e_e1_t1', from: 'entry_1', to: 'ticket_1', length: 40, width: 5, capacity: 40, baseTravelTime: 30, bidirectional: true },
      { id: 'e_e2_t2', from: 'entry_2', to: 'ticket_2', length: 40, width: 5, capacity: 40, baseTravelTime: 30, bidirectional: true },
      { id: 'e_t1_concourse', from: 'ticket_1', to: 'concourse', length: 50, width: 6, capacity: 50, baseTravelTime: 35, bidirectional: true },
      { id: 'e_t2_concourse', from: 'ticket_2', to: 'concourse', length: 50, width: 6, capacity: 50, baseTravelTime: 35, bidirectional: true },
      { id: 'e_concourse_p1', from: 'concourse', to: 'platform_1', length: 60, width: 8, capacity: 60, baseTravelTime: 40, bidirectional: true },
      { id: 'e_concourse_p2', from: 'concourse', to: 'platform_2', length: 50, width: 10, capacity: 80, baseTravelTime: 35, bidirectional: true },
      { id: 'e_concourse_p3', from: 'concourse', to: 'platform_3', length: 60, width: 8, capacity: 60, baseTravelTime: 40, bidirectional: true },
      { id: 'e_concourse_food', from: 'concourse', to: 'food_court', length: 40, width: 5, capacity: 40, baseTravelTime: 30, bidirectional: true },
      { id: 'e_p1_exit1', from: 'platform_1', to: 'exit_1', length: 50, width: 6, capacity: 50, baseTravelTime: 35, bidirectional: true },
      { id: 'e_p3_exit2', from: 'platform_3', to: 'exit_2', length: 50, width: 6, capacity: 50, baseTravelTime: 35, bidirectional: true },
      { id: 'e_p2_exit1', from: 'platform_2', to: 'exit_1', length: 70, width: 5, capacity: 40, baseTravelTime: 45, bidirectional: true },
      { id: 'e_p2_exit2', from: 'platform_2', to: 'exit_2', length: 70, width: 5, capacity: 40, baseTravelTime: 45, bidirectional: true },
    ],
  },
  agents: [
    { id: 'morning_rush_1', originId: 'entry_1', destinationId: 'platform_2', count: 250, walkingSpeed: 1.2, arrivalTime: 0, route: ['entry_1', 'ticket_1', 'concourse', 'platform_2'] },
    { id: 'morning_rush_2', originId: 'entry_2', destinationId: 'platform_2', count: 250, walkingSpeed: 1.2, arrivalTime: 5, route: ['entry_2', 'ticket_2', 'concourse', 'platform_2'] },
    { id: 'platform_1_board', originId: 'concourse', destinationId: 'platform_1', count: 100, walkingSpeed: 1.1, arrivalTime: 20, route: ['concourse', 'platform_1'] },
    { id: 'platform_3_board', originId: 'concourse', destinationId: 'platform_3', count: 100, walkingSpeed: 1.1, arrivalTime: 25, route: ['concourse', 'platform_3'] },
    { id: 'exit_rush_1', originId: 'platform_2', destinationId: 'exit_1', count: 200, walkingSpeed: 1.3, arrivalTime: 50, route: ['platform_2', 'exit_1'] },
    { id: 'exit_rush_2', originId: 'platform_2', destinationId: 'exit_2', count: 200, walkingSpeed: 1.3, arrivalTime: 52, route: ['platform_2', 'exit_2'] },
    { id: 'food_break', originId: 'platform_2', destinationId: 'food_court', count: 60, walkingSpeed: 1.0, arrivalTime: 40, route: ['platform_2', 'concourse', 'food_court'] },
  ],
};

const scenarios: Record<string, Scenario> = { stadium: stadiumScenario, festival: festivalScenario, railway: railwayScenario };

export function getScenario(id: string): Scenario | undefined { return scenarios[id]; }
export function getAllScenarios(): Scenario[] { return Object.values(scenarios); }
